var services = [
        { title: 'B.S. in Language Science', years: '2023–2026',
          topics: ['undergrad', 'department','college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: true },
        { title: 'Artificial Intelligence Task Force, UC Davis College of Letters and Science', years: '2025–2026',
          topics: ['college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Budget and Revenue Workgroup, UC Davis College of Letters and Science', years: '2025–2026',
          topics: ['college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Undergraduate Advisor', years: '2020–2026',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Colloquium Committee', years: '2020–2026',
          topics: ['department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Undergraduate Program Review Committee', years: '2023–2025',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Hiring Committee, with the Department of Statistics and Data Science', years: '2024–2025',
          topics: ['department', 'college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Graduate Admissions Committee', years: '2020–2024',
          topics: ['grad', 'department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'STEM Equity Learning Community (SELC Project)', years: '2023–2024',
          topics: ['undergrad'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Graduate Studies Fellowship Review Committee', years: '2022–2023',
          topics: ['grad', 'college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Graduate Studies Fellowship Review Committee', years: '2020–2021',
          topics: ['grad', 'college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false },
        { title: 'Undergraduate Mentor', years: '2016–2018',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false },
        { title: 'Undergraduate Studies Committee', years: '2016–2018',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false },
        { title: 'Graduate Student Representative', years: '2015–2016',
          topics: ['grad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false },
        { title: 'Graduate Studies Committee', years: '2015–2016',
          topics: ['grad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false }
    ];
