var services = [
        { title: 'B.S. in Language Science', years: '2023–2026',
          topics: ['undergrad', 'department','college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: true, link: '' },
        { title: 'Artificial Intelligence Task Force, UC Davis College of Letters and Science', years: '2025–2026',
          topics: ['college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Budget and Revenue Workgroup, UC Davis College of Letters and Science', years: '2025–2026',
          topics: ['college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Undergraduate Advisor', years: '2020–2026',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Colloquium Committee', years: '2020–2026',
          topics: ['department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Undergraduate Program Review Committee', years: '2023–2025',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Hiring Committee, with the Department of Statistics and Data Science', years: '2024–2025',
          topics: ['department', 'college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Graduate Admissions Committee', years: '2020–2024',
          topics: ['grad', 'department'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'STEM Equity Learning Community (SELC Project)', years: '2023–2024',
          topics: ['college','undergrad', 'profession'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Amicus Brief to the Supreme Court of the United States', years: '2023',
          topics: ['profession'],
          desc: '',
          logo: '', logoAlt: '', logoWidth: 90, firstPage: true, link: 'https://www.supremecourt.gov/DocketPDF/22/22-674/288484/20231031134947831_22-674%20-884%20Linguist%20Amici%20Brief%20Final.pdf' },
        { title: 'Organizing Committee, North American Conference in Iranian Linguistics (NACIL 3)', years: '2022–2023',
          topics: ['profession'],
          desc: '',
          logo: '', logoAlt: '', logoWidth: 90, firstPage: false, link: 'https://linguistics.ucla.edu/conference/nacil3/' },
        { title: 'Graduate Studies Fellowship Review Committee', years: '2022–2023',
          topics: ['grad', 'college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Graduate Studies Fellowship Review Committee', years: '2020–2021',
          topics: ['grad', 'college'],
          desc: '',
          logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, firstPage: false, link: '' },
        { title: 'Undergraduate Mentor', years: '2016–2018',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false, link: '' },
        { title: 'Undergraduate Studies Committee', years: '2016–2018',
          topics: ['undergrad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false, link: '' },
        { title: 'Graduate Student Representative', years: '2015–2016',
          topics: ['grad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false, link: '' },
        { title: 'Graduate Studies Committee', years: '2015–2016',
          topics: ['grad', 'department'],
          desc: '',
          logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, firstPage: false, link: '' }
    ];
