var courses = [
    { section: '2025-26', year: 2026, quarter: 'Winter', code: 'LIN 103B', title: 'Linguistic Analysis II',
      link: 'courses/lin103B_2026.html', topics: ['syntax'],
      desc: 'This course introduces students to the basic theoretical and mathematic foundations of natural language syntax. It covers the formal language theory and the Chomsky Hierarchy. Then we use the NLTK package in Python to create feature-based phrase structure grammars. The course only assumes some introductory background in linguistics.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 79, firstPage: false },
    { section: '2025-26', year: 2026, quarter: 'Winter', code: 'LIN 205', title: 'Language Learning in Humans and Machines',
      link: 'courses/lin205_2026.html', topics: ['learning', 'computational'],
      desc: 'This course provides a basic intro into computational models of language learning. We briefly review some known facts regarding child language development. We introduce three classes of models for language learning: rule-based symbolic models, Bayesian probabilistic models, and Neural Networks. We discuss prior and current research applying these models to better understand human language learning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 7, firstPage: true },
    { section: '2025-26', year: 2025, quarter: 'Fall', code: 'LIN 2', title: 'Language, the Mind, and Computers',
      link: 'courses/lin002_2025.html', topics: ['cogsci', 'computational'],
      desc: 'An introduction to the computational theory of the mind and major computational models that contribute to the study of language. An introduction to the basics of neural network models, information theory, and symbolic rule-based computation and their application to the study of language.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 241, firstPage: false },
    { section: '2025-26', year: 2025, quarter: 'Fall', code: 'LIN 141', title: 'Semantics',
      link: 'courses/lin141_2025F.html', topics: ['semantics'],
      desc: 'In this course we study how language conveys meaning and build models that mimic this process for better understanding its nature. We look at the meaning of sentences and how they are made from the contribution of individual words that make up the sentence. We also study how meaning is born in conversation and how each speaker\'s assumptions and conversational moves creates novel meaning. The course ends by discussing the role of social knowledge in creating meaning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 38, firstPage: true },
    { section: '2024-25', year: 2025, quarter: 'Spring', code: 'LIN 241', title: 'Advanced Semantics',
      link: 'courses/lin241_2025.html', topics: ['semantics'],
      desc: 'Advanced critical exploration of contemporary theories of linguistic semantics.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 8, firstPage: false },
    { section: '2024-25', year: 2025, quarter: 'Spring', code: 'LIN 001', title: 'Introduction to Linguistics',
      link: 'courses/lin001_2025.html', topics: ['cogsci'],
      desc: 'What is human language and why is it the way it is? The first half of the course introduces the classic subfields of linguistics addressing the question of what language is. The second half discusses subfields such as psycholinguistics, language acquisition, historical linguistics, and language variation that explain why human language is the way it is. Emphasis on developing analytic skills and critical thinking related to language.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 241, firstPage: false },
    { section: '2024-25', year: 2025, quarter: 'Winter', code: 'LIN 141', title: 'Semantics',
      link: 'courses/lin141_2025.html', topics: ['semantics'],
      desc: 'In this course we study how language conveys meaning and build models that mimic this process for better understanding its nature. We look at the meaning of sentences and how they are made from the contribution of individual words that make up the sentence. We also study how meaning is born in conversation and how each speaker\'s assumptions and conversational moves creates novel meaning. The course ends by discussing the role of social knowledge in creating meaning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 71, firstPage: false },
    { section: '2024-25', year: 2024, quarter: 'Fall', code: 'LIN 200', title: 'Foundations of Linguistics',
      link: 'courses/lin200_2024.html', topics: ['cogsci'],
      desc: 'Graduate course discussing foundational topics in linguistics including philosophy of science for linguists, the role of data and theory, history of linguistics, and current debates regarding the nature of language.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 5, firstPage: false },
    { section: '2023-24', year: 2024, quarter: 'Spring', code: 'LIN 105', title: 'Language Learning in Humans and Machines',
      link: 'courses/lin105_2024.html', topics: ['learning', 'computational'],
      desc: 'This course provides a basic intro into computational models of language learning. We briefly review some known facts regarding child language development. We introduce three classes of models for language learning: rule-based symbolic models, Bayesian probabilistic models, and Neural Networks. We discuss prior and current research applying these models to better understand human language learning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 43, firstPage: false },
    { section: '2023-24', year: 2024, quarter: 'Spring', code: 'LIN 231', title: 'Advanced Syntax',
      link: 'courses/lin231_2024.html', topics: ['syntax'],
      desc: 'This course provides a comprehensive and critical survey of contemporary theories of syntax. We start by discussing the foundations of theoretical syntax and specifically the role of linguistic evidence and data in theory building. We cover the following syntactic frameworks: minimalism, GPSG, LFG, CCG, HPSG, Construction Grammar, and Dependency Grammar.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 11, firstPage: false },
    { section: '2023-24', year: 2023, quarter: 'Fall', code: 'LIN 141', title: 'Semantics',
      link: 'courses/lin141_2024.html', topics: ['semantics'],
      desc: 'In this course we study how language conveys meaning and build models that mimic this process for better understanding its nature. We look at the meaning of sentences and how they are made from the contribution of individual words that make up the sentence. We also study how meaning is born in conversation and how each speaker\'s assumptions and conversational moves creates novel meaning. The course ends by discussing the role of social knowledge in creating meaning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 53, firstPage: false },
    { section: '2023-24', year: 2023, quarter: 'Fall', code: 'LIN 103B', title: 'Linguistic Analysis II',
      link: 'courses/lin103B_2023.html', topics: ['syntax'],
      desc: 'This course introduces students to the basic theoretical and mathematic foundations of natural language syntax. It covers the formal language theory and the Chomsky Hierarchy. Then introduces Combinatory Categorial Grammar (CCG) as a mildly context sensitive grammar that is useful for the analysis of natural language syntax. The second half of the course uses CCG to analyze some crosslinguistic examples. The course only assumes some introductory background in linguistics.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 92, firstPage: false },
    { section: '2022-23', year: 2023, quarter: 'Spring', code: 'LIN 001', title: 'Introduction to Linguistics',
      link: 'courses/lin001_2023.html', topics: ['cogsci'],
      desc: 'What is human language and why is it the way it is? The first half of the course introduces the classic subfields of linguistics addressing the question of what language is. The second half discusses subfields such as psycholinguistics, language acquisition, historical linguistics, and language variation that explain why human language is the way it is. Emphasis on developing analytic skills and critical thinking related to language.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 243, firstPage: false },
    { section: '2022-23', year: 2023, quarter: 'Spring', code: 'LIN 241', title: 'Advanced Semantics',
      link: 'courses/lin241_2023.html', topics: ['semantics'],
      desc: 'Advanced critical exploration of contemporary theories of linguistic semantics.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 5, firstPage: false },
    { section: '2022-23', year: 2022, quarter: 'Fall', code: 'LIN 141', title: 'Semantics',
      link: 'courses/lin141_2023.html', topics: ['semantics'],
      desc: 'In this course we study how language conveys meaning and build models that mimic this process for better understanding its nature. We look at the meaning of sentences and how they are made from the contribution of individual words that make up the sentence. We also study how meaning is born in conversation and how each speaker\'s assumptions and conversational moves creates novel meaning. The course ends by discussing the role of social knowledge in creating meaning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 70, firstPage: false },
    { section: '2022-23', year: 2022, quarter: 'Fall', code: 'LIN 200', title: 'Foundations of Linguistics',
      link: 'courses/lin200_2022.html', topics: ['cogsci'],
      desc: 'Graduate course discussing foundational topics in linguistics including philosophy of science for linguists, the role of data and theory, history of linguistics, and current debates regarding the nature of language.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 9, firstPage: false },
    { section: '2021-22', year: 2022, quarter: 'Spring', code: 'LIN 001', title: 'Introduction to Linguistics',
      link: 'courses/lin001_2022.html', topics: ['cogsci'],
      desc: 'What is human language and why is it the way it is? The first half of the course introduces the classic subfields of linguistics addressing the question of what language is. The second half discusses subfields such as psycholinguistics, language acquisition, historical linguistics, and language variation that explain why human language is the way it is. Emphasis on developing analytic skills and critical thinking related to language.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 226, firstPage: false },
    { section: '2021-22', year: 2022, quarter: 'Fall', code: 'LIN 131', title: 'Introduction to Syntactic Theory',
      link: 'courses/lin131_2022.html', topics: ['syntax'],
      desc: 'Why is it that you can easily understand this sentence, but not the following: "one this not but sentence this understand easily can you that it is why"? What determines the way we order words to convey our thoughts? How do world languages differ in this respect? This course introduces the basic concepts of syntactic theory; a theory that explains how languages structure and order their elements. We start with linguistic evidence and what counts as data for a syntactic theory. We cover mathematical formalisms that have been developed for modeling language structure and we look at different languages to understand how a syntactic theory can explain linguistic phenomena in languages around the world.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 84, firstPage: false },
    { section: '2021-22', year: 2022, quarter: 'Fall', code: 'LIN 141', title: 'Semantics',
      link: 'courses/lin141_2022.html', topics: ['semantics'],
      desc: 'Linguistic study of meanings of words and phrases. Meanings expressed by lexical items and derivational and inflectional morphology. Contribution of argument structure, quantification, and coordination to meaning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 56, firstPage: false },
    { section: '2021-22', year: 2022, quarter: 'Spring', code: 'LIN 241', title: 'Advanced Semantics',
      link: 'courses/lin241_2022.html', topics: ['semantics'],
      desc: 'Advanced critical exploration of contemporary theories of linguistic semantics.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 11, firstPage: false },
    { section: '2020-21', year: 2021, quarter: 'Spring', code: 'LIN 141', title: 'Semantics',
      link: 'courses/lin141_2021.html', topics: ['semantics'],
      desc: 'Linguistic study of meanings of words and phrases. Meanings expressed by lexical items and derivational and inflectional morphology. Contribution of argument structure, quantification, and coordination to meaning.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 61, firstPage: false },
    { section: '2020-21', year: 2021, quarter: 'Winter', code: 'LIN 231', title: 'Advanced Syntax',
      link: 'courses/lin231_2021.html', topics: ['syntax'],
      desc: 'This course provides a comprehensive and critical survey of contemporary theories of syntax. We start by discussing the foundations of theoretical syntax and specifically the role of linguistic evidence and data in theory building. We cover formal language theory and the theory of government and binding. We then survey the following current syntactic frameworks: minimalism, GPSG, LFG, CCG, HPSG, Construction Grammar, and Dependency Grammar. The course also discusses computational and psycholinguistic applications of these frameworks.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 16, firstPage: false },
    { section: '2020-21', year: 2021, quarter: 'Winter', code: 'LIN 131', title: 'Introduction to Syntactic Theory',
      link: 'courses/lin131_2021.html', topics: ['syntax'],
      desc: 'Why is it that you can easily understand this sentence, but not the following: "one this not but sentence this understand easily can you that it is why"? What determines the way we order words to convey our thoughts? How do world languages differ in this respect? This course introduces the basic concepts of syntactic theory; a theory that explains how languages structure and order their elements. We start with linguistic evidence and what counts as data for a syntactic theory. We cover mathematical formalisms that have been developed for modeling language structure and we look at different languages to understand how a syntactic theory can explain linguistic phenomena in languages around the world.',
      logo: 'image/UCDavis.png', logoAlt: 'UC Davis logo', logoWidth: 90, students: 47, firstPage: false },
    { section: '2019-20', year: 2020, quarter: 'Spring', code: 'LING 132', title: 'Psychosemantics (with Kathryn Davidson)',
      link: '', topics: ['cogsci', 'semantics'],
      desc: 'Explores issues at the interface of linguistic semantics, pragmatics and psychology. Introduces how the analysis of meaning has been pursued by linguists and psychologists. Focuses on topics that are both of central interest to theoretical linguistics and the target of experimental research.',
      logo: 'image/harvard_seal.png', logoAlt: 'Harvard University seal', logoWidth: 80, students: 10, firstPage: false },
    { section: '2019-20', year: 2019, quarter: 'Fall', code: 'LING 106', title: 'The Knowledge of Meaning',
      link: 'courses/ling106.html', topics: ['semantics'],
      desc: 'An introduction to formal semantics and pragmatics. The course covers the basics of predicate logic, lambda calculus, possible worlds, Gricean pragmatics, speech acts, and social meaning.',
      logo: 'image/harvard_seal.png', logoAlt: 'Harvard University seal', logoWidth: 80, students: 40, firstPage: false },
    { section: '2018-19', year: 2018, quarter: 'Spring', code: 'LING 111', title: 'First Language Acquisition',
      link: 'courses/ling111.html', topics: ['learning'],
      desc: 'An introduction to language development in infants and preschool children. Topics include development of sound perception and production, syntactic and semantic development, pragmatic development, bilingualism, and sign language acquisition. Emphasis on developing a research project while paying attention to best practices at different stages of scientific research.',
      logo: 'image/harvard_seal.png', logoAlt: 'Harvard University seal', logoWidth: 80, students: 80, firstPage: false },
    { section: '2018-19', year: 2018, quarter: 'Fall', code: 'LING 83', title: 'Language, Structure, and Cognition',
      link: 'courses/ling83.html', topics: ['cogsci'],
      desc: 'Introduction to linguistics with emphasis on cognition and computation. The first half of the course introduces the classic subfields of linguistics while the second half surveys applications of linguistic theory to problems in cognitive science. Emphasis on developing analytic skills and critical thinking.',
      logo: 'image/harvard_seal.png', logoAlt: 'Harvard University seal', logoWidth: 80, students: 14, firstPage: false },
    { section: '2017-18', year: 2018, quarter: 'Spring', code: 'LING 140', title: 'Learning to Speak: Introduction to Language Acquisition',
      link: 'courses/ling140.html', topics: ['learning'],
      desc: 'An introduction to language development in infants and preschool children. Topics include development of sound perception and production, syntactic and semantic development, pragmatic development, bilingualism, and sign language acquisition. Emphasis on developing a research project while paying attention to best practices at different stages of scientific research.',
      logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, students: 15, firstPage: false },
    { section: '2017-18', year: 2017, quarter: 'Fall', code: 'LING 196', title: 'Introduction to Research for Undergraduates',
      link: 'courses/ling196.html', topics: [],
      desc: 'A course that introduced subfields of linguistics to undergraduates with guest lectures from the faculty at Stanford linguistics in each subfield.',
      logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, students: 12, firstPage: false },
    { section: '2016-2017', year: 2017, quarter: 'Summer', code: 'LING 40S', title: 'Lab in Critical and Scientific Thinking',
      link: 'courses/ling40s.html', topics: [],
      desc: 'A summer course suitable for beginning college and finishing high school students interested in using language as a topic to develop their analytic, critical, and scientific skills.',
      logo: 'image/stanford.png', logoAlt: 'Stanford University logo', logoWidth: 120, students: 10, firstPage: false }
  ];
